name: CI
on: [push, pull_request]

#env:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "17"
          cache: "npm"
      - run: npm ci

      - run: npm test
      # db/*.sql
      - run: cd db && bash ./test.sh
